name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            build_args: --linux
          - os: macos-latest
            build_args: --mac
          - os: windows-latest
            build_args: --win

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.0
          cache: npm

      - name: apt-update
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update

      - name: autoremove
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt autoremove

      - name: Install Linux packaging dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y libarchive-tools rpm

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Publish Electron app
        run: npx electron-builder ${{ matrix.build_args }} --publish always
        env:
          GH_TOKEN: ${{ github.token }}
